parameters:
    netgen_siteaccess_routes.event_listener.request.class: Netgen\Bundle\SiteAccessRoutesBundle\EventListener\RequestListener

    netgen_siteaccess_routes.matcher.class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Matcher

    netgen_siteaccess_routes.voter.default_siteaccess.class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\DefaultSiteAccessVoter
    netgen_siteaccess_routes.voter.siteaccess.class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\SiteAccessVoter
    netgen_siteaccess_routes.voter.siteaccess_group.class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\SiteAccessGroupVoter

services:
    netgen_siteaccess_routes.event_listener.request:
        class: "%netgen_siteaccess_routes.event_listener.request.class%"
        arguments:
            - "@netgen_siteaccess_routes.matcher"
        tags:
            - { name: kernel.event_subscriber }

    netgen_siteaccess_routes.matcher:
        class: "%netgen_siteaccess_routes.matcher.class%"
        arguments:
            - []

    netgen_siteaccess_routes.voter.default_siteaccess:
        class: "%netgen_siteaccess_routes.voter.default_siteaccess.class%"
        arguments:
            - "%ezpublish.siteaccess.default%"
        tags:
            - { name: netgen_siteaccess_routes.voter }

    netgen_siteaccess_routes.voter.siteaccess:
        class: "%netgen_siteaccess_routes.voter.siteaccess.class%"
        tags:
            - { name: netgen_siteaccess_routes.voter }

    netgen_siteaccess_routes.voter.siteaccess_group:
        class: "%netgen_siteaccess_routes.voter.siteaccess_group.class%"
        arguments:
            - "%ezpublish.siteaccess.groups_by_siteaccess%"
        tags:
            - { name: netgen_siteaccess_routes.voter }
