language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0

# test only master (+ pull requests)
branches:
  only:
    - master

# composer setup
before_install:
    - phpenv config-add travis.php.ini
    - composer self-update

# install dependencies
install: travis_wait composer install --prefer-source

# execute phpunit as the script command
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false
